### ISSUE TITLE
Safari : text shadow bug

### ISSUE THREAD

**Issue by amcooper** [amcooper/about_me#10]
Safari/Mac
In panels, navbar neon text shadow appears 150 pixels below text. 

Is it due to the 150px argument of the text-shadow in the CSS? If so, why isn't it showing up in other browsers?

**Comment by amcooper** [comment]
It is due to the 150px blur radius yes. Changing it to 140px does the trizzick:
```css
.nn {
  font-family: 'Roboto Mono', monospace;
  color: #EEDDE0;
  text-shadow: 0 0 9.0px #EC637B, 
    0 0 3.0px rgba(230, 161, 173, 0.41), 
    0 0 30.0px #E6A1AD, 
    0 0 140.0px #F36780, 
    1.5px 2.7px 1.5px rgba(0, 0, 0, 0.5);  
}
```
