### ISSUE TITLE
Contact icons

### ISSUE THREAD

**Issue by amcooper** [amcooper/about_me#18]
1. Should be rose quartz rather than black. Will have to do this in PhotoShop.
2. Should be smaller so they don't misalign the grid, as it were.

**Comment by amcooper** [comment]
1. In GIMP: Colorize > 
2. 
``` css
#fContactLinks ul li {
  display: block;
  height: 64px;
  /*margin-top: 40px;*/
  margin-bottom: 10px;
}
```
